apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-secretcount-ns-policy
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-secretcount-ns-rule
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - nirmata
              - cs-operator
              - kube-system
              - kyverno 
      context:
        - name: secretcount
          apiCall:
            urlPath: "/api/v1/namespaces/{{request.object.metadata.name}}/secrets"
            jmesPath: "items || '' | length(@)"
      validate:
        message: >-
          There are no secrets defined in the {{request.namespace}} namespace. Use kubernetes secrets to define your application secrets"
        deny:
          conditions:
            any:
              - key: "{{ secretcount }}"
                operator: Equals
                value: 0
