apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    policies.kyverno.io/title: Required Drop Capabilities
    policies.kyverno.io/category: DISA Compliance
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.9.0
    kyverno.io/kubernetes-version: "1.24"
    policies.kyverno.io/subject: Pod
  name: disallow-capabilities
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: required-drop-capabilities
      match:
        any:
        - resources:
            kinds:
              - Pod
      exclude:
        any:
        - resources:
            kinds:
              - Pod
            namespaces:
              - nirmata
              - nirmata-system
              - kube-system
              - kyverno 
      preconditions:
        all:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: NotEquals
          value: DELETE
      validate:
        message: >-
          ""
        foreach:
          - list: request.object.spec.[ephemeralContainers, initContainers, containers][]
            deny:
              conditions:
                any:
                - key: SETGID
                  operator: AnyNotIn
                  value: "{{ element.securityContext.capabilities.drop[].to_upper(@) || `[]` }}"
                - key:  SETUID
                  operator: AnyNotIn
                  value: "{{ element.securityContext.capabilities.drop[].to_upper(@) || `[]` }}"

