apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: validate-run-instruction
  annotations:
    policies.kyverno.io/title: Validate RUN instruction in Dockerfile
    policies.kyverno.io/category: DISA Compliance
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      This policy checks if the Dockerfile contains a RUN instruction. If the RUN instruction is not present, the policy fails.
spec:
  rules:
    - name: validate-run-instruction
      match:
        any:
        - (Stages[].Commands[] | length(@) > `0`): true
      assert:
        any:
        - message: RUN instruction is present in the Dockerfile
          check:
            (Stages[].Commands[?Name=='RUN'][] | length(@) > `0`): false
